project:
  type: website
  output-dir: docs
  title: "Alessandro Zito"


website:
  title: "Alessandro Zito"
  favicon: images/painting.jpeg
  description: "Alessandro Zito is a statistician and a data scientist working on cancer genomics and ecology."
  navbar: 
    title: Ale Zito
    logo: images/painting.jpeg
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: software.qmd
        text: Software
      - href: talks.qmd
        text: Talks
      - href: colabs.qmd
        text: Collaborators
    right:    
      - href: artwork.qmd
        text: alezitoart
    google-analytics: "392591573"
    site-url: https://alessandrozito.github.io/web/
  body-footer: |
      <center>
      <br>
      **Address**: <br>
      655 Huntington Ave, Boston, MA 02115, United States <br>
      **Email**: <br>
      [azito@hsph.harvard.edu](mailto: azito@hsph.harvard.edu) <br>
      **Links**:<br>
      [{{< ai google-scholar size=31px >}}](https://scholar.google.com/citations?user=ciOk2IQAAAAJ&hl=en) &nbsp; 
      [{{< iconify fa6-brands github size=30px >}}](https://github.com/alessandrozito) &nbsp; 
      [{{< iconify fa6-brands linkedin size=30px >}}](https://www.linkedin.com/in/alessandro-zito-92b250153/) &nbsp; 
      [{{< ai researchgate size=31px >}}](https://www.researchgate.net/profile/Alessandro-Zito-7) &nbsp; 
      [{{< ai orcid size=31px >}}](https://orcid.org/0000-0001-8515-6503) 
      </center>
  page-footer:
    left: "© 2024 By Alessandro Zito. All rights reserved."
    right: 
      - icon: envelope-at
        text: "azito@hsph.harvard.edu"
        href: "mailto: azito@hsph.harvard.edu"
      
include-in-header: 
  - text: |
      <meta name="google-site-verification" content="8VlySRWcAYNJqMvbPEh8XS0Dl_QPeEuigWeOuSLnGMg" />    
      
format:
  html:
    theme: [cosmo, styles.css]
    fontsize: 1.1em
    linestretch: 1.6
    max-width: 36em
    backgroundcolor: "#F6F9FB"
    css: styles.css
    toc: false
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px
    favicon: images/painting.jpeg



editor: visual


