## Research highlights {.central}

I develop statistical methodologies to aid scientific discovery.

My current line of work involves a combination of theory, methods, and application. These include

- Probabilistic machine learning methods for large-scale biodiversity assessment
- Generative stochastic process frameworks for genomic data
- Bayesian Non-negative matrix factorization algorithms
- Flexible nonparametric models for density estimation
- Biological investigation of somatic modification in cancer and RNA editing

In recognition of my doctoral dissertation, I received the [Savage Award in Applied Methodology](https://bayesian.org/project/savage-award/) at the 2025 Joint Statistical Meeting. Read it below!

[Ph.D. Dissertation](files/thesis_alezito.pdf){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Dissertation"} [Ph.D. defense slides](files/defense_alezito.pdf){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Defense slides"} [Google Scholar](https://scholar.google.com/citations?user=ciOk2IQAAAAJ&hl=en){.btn .btn-outline-primary .btn role="button" data-toggle="tooltip" title="Google scholar"}

## Publications and manuscripts {.central}

#### [Preprints]{.blue} {.central}

1.  [Zito, A.]{style="text-decoration: underline;"}, Rigon T., Roslin T., Niittynen, P., Hebert P. D. N.,  iBOL consortium, Ovaskainen O. and Dunson D. B. (2026). **Predicting global biodiversity via Hubbell regression**. [*Submitted to ?? :)*]{.black} [\[bioRxiv\]](https://www.biorxiv.org/content/)

1. [Zito, A.]{style="text-decoration: underline;"}, Parmigiani, G. and Miller, J. W. (2025). **Poisson process factorization for mutational signature analysis with genomic covariates**. [*Journal of the American Statistical Association ACS, Major Revision*]{.black}.  [\[arXiv\]](https://arxiv.org/abs/2510.26090)

1.  Xue, C., [Zito, A.]{style="text-decoration: underline;"} and Miller, J. W. (2024). **Improved control of Dirichlet location and scale near the boundary**. [*Bayesian Analysis, R&R*]{.black} [\[ArXiv\]](https://arxiv.org/abs/2410.13050) [\[GitHub\]](https://github.com/casxue/ImprovedDirichlet) - [*JSM 2025 SBSS student paper competition award received by Cathy Xue*]{.orange}

2.  [Zito, A.]{style="text-decoration: underline;"} and Miller, J. W. (2024). **Compressive Bayesian non-negative matrix factorization for mutational signature analysis**. [*Biometrics, Major Revision*]{.black}. [\[ArXiv\]](https://arxiv.org/abs/2404.10974) [\[GitHub\]](https://github.com/alessandrozito/CompressiveNMF)

------------------------------------------------------------------------

#### [Articles in refereed journals]{.blue} {.central}

1. Modi, A., [Zito, A.]{style="text-decoration: underline;"}, and Parmigiani, G. (2026). **Pan-Cancer Genomic Scars of Alternative End Joining and Single-Strand Annealing**. [*BMC Cancer*]{.black}, in press [\[bioRxiv\]](https://www.biorxiv.org/content/10.64898/2026.05.22.727283v1)

1.  Orsholm, J.\*, [Zito, A.]{style="text-decoration: underline;"}\*, Somervuo, P., Braga M, Chazlot, N, Roslin, T. and Furneaux, B. (2025). **Discovering the unseen: a performance comparison of taxonomic classification methods under unknown DNA barcodes**. [*Methods in Ecology and Evolution*]{.black}, in press [\[Pub\]](https://doi.org/10.1111/2041-210x.70358) [\[bioRxiv\]](https://doi.org/10.1101/2025.10.13.681976)

1.  Lee, C. J., [Zito, A.]{style="text-decoration: underline;"}, Sang, H., and Dunson, D. B. (2025). **Logistic-Beta Processes for dependent random probabilities with beta marginals**. [*Bayesian Analysis*]{.black}, *20*(4), 1345--1369 [\[Pub\]](https://doi.org/10.1214/25-BA1541) [\[ArXiv\]](https://arxiv.org/pdf/2402.07048.pdf) [\[GitHub\]](https://github.com/changwoo-lee/logisticbeta-reproduce) - [*Lindley Prize 2025 - honorable mention*]{.orange}

1.  [Zito, A.]{style="text-decoration: underline;"}, Greaves, D., Soriano, J. and Richardson, L. (2025). **Pareto optimal proxy metrics**. *Applied Stochastic Models in Business and Industry*, 41: e70003 [\[Pub\]](https://onlinelibrary.wiley.com/doi/10.1002/asmb.70003)[\[ArXiv\]](https://arxiv.org/pdf/2307.01000.pdf)

1.  [Zito, A.]{style="text-decoration: underline;"}, Rigon, T., and Dunson, D. B. (2026). **Bayesian nonparametric modeling of latent partitions via Stirling-gamma priors**. [*Bayesian Analysis*]{.black}, *21*(1) 139--166, [\[Pub\]](https://projecteuclid.org/journals/bayesian-analysis/advance-publication/Bayesian-Nonparametric-Modeling-of-Latent-Partitions-via-Stirling-Gamma-Priors/10.1214/24-BA1463.full)[\[ArXiv\]](https://arxiv.org/pdf/2306.02360.pdf) [\[R Package\]](https://github.com/alessandrozito/ConjugateDP)

1.  [Zito, A.]{style="text-decoration: underline;"}, Rigon, T., and Dunson, D. B. (2023). **Inferring taxonomic placement from DNA barcoding aiding in discovery of new taxa**. [*Methods in Ecology and Evolution*]{.black}, *14*, 529--542. [\[Pub\]](https://doi.org/10.1111/2041-210X.14009) [\[ArXiv\]](https://arxiv.org/abs/2201.09782) [\[Code\]](https://doi.org/10.5281/zenodo.7150668) [\[R package\]](https://github.com/alessandrozito/BayesANT). - [*Best poster award at IBSA2022 world meeting.*]{.orange}

1.  [Zito, A.]{style="text-decoration: underline;"}, Rigon, T., Ovaskainen, O., and Dunson, D. B. (2023). **Bayesian modeling of sequential discoveries**. [*Journal of the American Statistical Association (Theory & Methods)*]{.black}, *118*(544), 2521--2532. [\[Pub\]](https://doi.org/10.1080/01621459.2022.2060835) [\[Manuscript\]](https://drive.google.com/file/d/1pqPzylh3gu1NMkEY-vZwTJthd_pBPgAW/view) [\[R package\]](https://github.com/alessandrozito/BNPvegan) - [*Best Student/Postdoc Contributed paper award at IBSA2021 world meeting.*]{.orange} - [*BEST award for Ph.D. student research 2022, Dept. of Statistical Science, Duke University*]{.pink}

#### [Refereed conference proceedings and discussions]{.blue} {.central}

1.  [Zito, A.]{style="text-decoration: underline;"}, Xue, C., and Miller, J. W. (2025). **Accounting for Transcriptional Asymmetries in Mutational Signature Analysis Using Compressive Bayesian Non-negative Matrix Factorization** In: di Bella, E., Gioia, V., Lagazio, C., Zaccarin, S. (eds) [\*Statistics for Innovation IV. SIS 2025. Italian Statistical Society Series on Advances in Statistics](https://link.springer.com/chapter/10.1007/978-3-031-96033-8_81). Springer, Cham.

2.  [Zito, A.]{style="text-decoration: underline;"} and Miller, J. W. (2024). **Discussion to "Sparse Bayesian factor analysis when the number of factors is unknown"** by Fruhwirth--Schnatter, S., Hosszejini, D., and Lopes, F. L., [*Bayesian Analysis*]{.black} [\[Pub\]](https://projecteuclid.org/journals/bayesian-analysis/advance-publication/Sparse-Bayesian-Factor-Analysis-When-the-Number-of-Factors-Is/10.1214/24-BA1423.full)

3.  [Zito, A.]{style="text-decoration: underline;"}, Rigon, T. and Dunson, D. B. (2021). **Modelling of accumulation curves through Weibull survival functions.** In [*Book of Short Papers of the Italian Statistical Society 2021*]{.black} (Perna, C., Salvati, N. and Schirripa Spagnolo, F., editors). ISBN: 9788891927361. [\[Link part 1\]](%22https://it.pearson.com/content/dam/region-core/italy/pearson-italy/pdf/Docenti/Universit%C3%A0/pearson-sis-book-2021-parte-1.pdf%22) [\[Link part 2\]](https://it.pearson.com/content/dam/region-core/italy/pearson-italy/pdf/Docenti/Universit%C3%A0/pearson-sis-book-2021-parte-2.pdf)

------------------------------------------------------------------------

#### [Manuscripts in preparation]{.darkred} {.central}

1.  **Zito, A.**, Parmigiani, G., Miller, J. W. and Samur, M. (2026+). Joint analysis of mutational process in DNA and RNA from multiple myeloma.

------------------------------------------------------------------------
