### List of talks and presentations

[2025]{.blue}

-   [JSM2025](https://ww2.amstat.org/meetings/jsm/2025/index.cfm), Nashville, TN - *Ecological Modeling via Bayesian Nonparametric Species Sampling Priors* - [Invited talk]{.gred} - The Savage Dissertation Award.  

-   [BNP14](https://bnp14.org/program/), Los Angeles, CA - *Topography-dependent mutational signature analysis via Poisson process factorization* - [Contributed talk]{.gyellow} 

-   [ENAR2025](https://www.enar.org/meetings/spring2025/), New Orleans, LA - *Compressive Bayesian non-negative matrix factorization for mutational signature analysis.* - [Contributed talk]{.gyellow} 

-   [Brown University, Data Science Initiative](https://events.brown.edu/dsi/event/291116-data-matters-seminar-compressive-bayesian-n), Providence, RI, USA - *Compressive Bayesian non-negative matrix factorization for mutational signature analysis.* - [Invited seminar]{.gred} [Video](https://www.youtube.com/watch?v=3y8KRxawYYk)


[2024]{.blue}

-   [Cattolica University of the Sacred Hearth](https://www.unicatt.it/eventi/ateneo/milano/2024/compressive-bayesian-non-negative-matrix.html), Milan, Italy - *Compressive Bayesian non-negative matrix factorization for mutational signature analysis.* - [Invited seminar]{.gred}

-   [ICSDS2024](https://sites.google.com/view/ims-icsds2024/home), Nice, France - *Compressive Bayesian non-negative matrix factorization for mutational signature analysis.* - [Contributed talk]{.gyellow}

-   [ISBA2024](https://www.unive.it/web/en/2208/home), Venice, Italy - *Compressive Bayesian non-negative matrix factorization for mutational signature analysis.* - [Invited talk]{.gred}

-   [ISBA2024](https://www.unive.it/web/en/2208/home), Venice, Italy - *Bayesian nonparametric modeling of latent partitions via Stirling-gamma priors.* - [Poster]{.ggreen}

[2023]{.blue}

-   [CMstat2023](https://www.cmstatistics.org/CMStatistics2023/), Berlin, Germany - *Bayesian nonparametric modeling of latent partitions via Stirling-gamma priors.* - [Invited talk]{.gred}

-   [EcoSta2023](https://www.cmstatistics.org/EcoSta2023/), Tokyo, Japan - *Bayesian nonparametric modeling of latent partitions via Stirling-gamma priors.* - [Invited talk]{.gred}

-   [NESS2023](https://archive.nestat.org/symposium2023/html/), Boston, MA, USA - *Bayesian nonparametric modeling of latent partitions via Stirling-gamma priors.* - [Invited talk]{.gred}

[2022]{.blue}

-   [CMstat2022](https://www.cmstatistics.org/CMStatistics2022/), London, UK - *Inferring taxonomic placement from DNA barcoding aiding in discovery of new taxa.* - [Invited talk]{.gred}

-   [BNP13](https://midas.mat.uc.cl/bnp13/), Puerto Varas, Chile - *Bayesian nonparametric modeling of latent partitions via Stirling-gamma priors.* - [Poster]{.ggreen}

-   [ISBA2022](https://isbawebmaster.github.io/ISBA2022/), Montreal, Canada - *Inferring taxonomic placement from DNA barcoding aiding in discovery of new taxa.* - [Poster]{.ggreen}

-   [Luomos SYKE Machine Learning seminar II](https://www.syke.fi/en-US/Current/Events/LuomusSYKE_Machine_learning_seminar_II(61819)), Virtual - *Taxonomic classification methods for DNA sequences.* - [Contributed talk]{.gyellow}

[2021]{.blue}

-   [ISBA2021](https://events.stat.uconn.edu/ISBA2021/), virtual - *Bayesian modeling of sequential discoveries.* - [Contributed talk]{.gyellow}

-   [ISBA2021](https://events.stat.uconn.edu/ISBA2021/), virtual - *Inferring taxonomic placement from DNA barcoding aiding in discovery of new taxa.* - [Contributed talk]{.gyellow}

------------------------------------------------------------------------

### Sessions organized and chaired

-   [JSM2025](https://ww2.amstat.org/meetings/jsm/2025/index.cfm), Nashville, TN. Organizer and chair of **Advances in Bayesian Facotrization methods in Genomics and Medicine**, invited session . Speakers:
    -   [Adolphus Wagala](https://scholar.google.com/citations?user=Uq2lFd4AAAAJ&hl=en), Dana-Farber Cancer Institute - *Bayesian boolean matrix factorization for copy number alterations in multiple myeloma*.
    -   [Jonathan Huggins](http://jhhuggins.org/), Boston Univeristy - *Structurally aware robust rank selection for probabilistic matrix factorization*.
    -   [Sarah Urbut](https://scholar.google.com/citations?user=iafjMbAAAAAJ&hl=en), Broad Institute <-- **Replaced by me**.
    -   [Niccolo Anceschi](https://niccoloanceschi.github.io/), Duke University - *Spectral decomposition-assisted multi-study factor analysis*.
    -   *Discussion* by [Peter Carbonetto](https://pcarbo.github.io/), The University of Chicago University.
    
-   [ISBA2024](https://www.unive.it/web/en/2208/home), Venice, Italy. Organizer and chair of **Bayesian methods in Ecology**, invited session . Speakers:
    -   [Bokgyeong Kang](https://bokgyeong.github.io/), Duke University - *Analyzing whale calls through Hawkes processes modeling*.
    -   [Michele Peruzzi](https://mkln.it/), University of Michigan - *Bayesian multi-species N-mixture models for large scale spatial data in community ecology*.
    -   [Narmadha M. Mohankumar](https://scholar.google.com/citations?user=e61OCNUAAAAJ&hl=en), Pacific Northwest National Lab. - *Using machine learning to model nontraditional spatial dependence in occupancy data*.

------------------------------------------------------------------------
